#!/usr/bin/env bash

# Source the common useful functions (aka. umacros)
[[ ! -f ./lib/umacros ]] && {
  echo -e "Cannot find umacros.\nPlease make sure you ran this installer from within the script directory"
}

source ./lib/umacros



# Error if dependencies do not exist
if ! command -v stow &>/dev/null; then
  paint fg red "[ERR] Stow is not installed. Please install it using your package manager before running this script."
fi



# You need a default repo directory supplied as the first argument
repo="$1"

# Error if no repo supplied
[[ -z "$repo" ]] && {
  paint fg red "[ERR] No repo specified. Please insert a valid directory as the first argument."
  exit 1
}

# Error if too many arguments
[[ $# -gt 1 ]] && {
  paint fg red "[ERR] Too many arguments"
  exit 1
}

# Error if supplied repo is not a directory
[[ ! -d "$repo" ]] && {
  paint fg red "[ERR] '$1' is not a valid directory"
  exit 1
}



# Makes sure installation directories exist ( or creates them otherwise )
INSTALL_DIR="$HOME/.local/bin"
LIB_DIR="$HOME/.local/lib"
CONFIG_DIR="$HOME/.config/udots"
DEF_CONFIG_DIR="$HOME/.local/share/udots"

checkDir "$INSTALL_DIR"
checkDir "$LIB_DIR"
checkDir "$CONFIG_DIR"
checkDir "$DEF_CONFIG_DIR"



# Copy files over to installation directories
add () {
  local target="$1"
  local targetName="${target//*\//}"
  local dest="$2"

  if [[ ! -f "$dest/$targetName" ]]; then
    cp "$target" "$dest"
    paint fg green "[Installed]" " $targetName"
  else
    paint fg yellow "[Warning]" " '$targetName' is already installed"
  fi
}


add udots "$INSTALL_DIR"
chmod +x "$INSTALL_DIR/udots"

add config/udots-config.sh "$CONFIG_DIR"
add lib/umacros "$LIB_DIR"



# Add supplied repo to config file
sed -i "s|^REPO_DIR=*|REPO_DIR=\"$repo\"|" "$CONFIG_DIR/udots-config.sh"



# Check if $HOME/.local/bin is in PATH
while read line; do
  [[ "$line" =~ "$HOME/.local/bin" ]] && {
    localExists=1
    break
  }
done <<< "${PATH//:/$'\n'}"

[[ -z "$localExists" ]] && {
  paint fg yellow "[Notice] You don't have ~/.local/bin in your PATH variable. Please make sure you append it to PATH."
}
