#!/usr/bin/env bash

[[ ! -f ./lib/umacros ]] && {
  echo -e "Cannot find umacros.\nPlease make sure you ran this installer from within the script directory"
}

source ./lib/umacros

add () {
  local target="$1"
  local targetName="${target//*\//}"
  local dest="$2"

  [[ ! -f "$dest/$targetName" ]] && { 
    cp "$target" "$dest"
    paint fg green "[Installed]" "$targetName"
  }
}

INSTALL_DIR="$HOME/.local/bin"
LIB_DIR="$HOME/.local/lib"
CONFIG_DIR="$HOME/.config/udots"
DEF_CONFIG_DIR="$HOME/.local/share/udots"

checkDir "$INSTALL_DIR"
checkDir "$LIB_DIR"
checkDir "$CONFIG_DIR"
checkDir "$DEF_CONFIG_DIR"

add udots "$INSTALL_DIR"
chmod +x "$INSTALL_DIR/udots"

add config/udots-config.sh "$CONFIG_DIR"
add lib/umacros "$LIB_DIR"
