#!/usr/bin/env bash

CONFIG="$HOME/.config/udots/"
REPO="$HOME/git/termux-cfg"
VERSION="0.3"

checkDir () {
  if [[ ! -d "$1" ]]; then
    mkdir -p "$1"
  fi
}

checkDir "$CONFIG"
checkDir "$REPO"

fullPath () {
  # Remove ending /
  fullTarget="$(echo $1 | sed 's|/$||')"

  if [[ -d "$fullTarget" ]]; then
    if [[ "$fullTarget" =~ "/" ]]; then
      # Split last item and path
      IFS=" " read -d "" -r dirName target <<< "${fullTarget%\/*} ${fullTarget##*\/}"
      echo "$(cd "$dirName"; pwd)/$target"
    else
      dirName="$fullTarget"
      echo "$(cd "$dirName"; pwd)"
    fi
  else
    echo "$(pwd)"
  fi

}

case "$1" in
  "--add"|"-a")
    pkgName="$2"
    rawPath="$3"
    pkgPath="$(fullPath "$rawPath")"
    
    lastPathItem="${pkgPath##*\/}"
    newPath="$(echo "$pkgPath" | sed "s|^$HOME/\?||;s|/$lastPathItem$||")"

    mkdir -p "$REPO/$pkgName/$newPath"

    mv "$rawPath" "$REPO/$pkgName/$newPath"

    stow -d "$REPO" -t "$HOME" "$pkgName"

    # =========================================
    # DEBUGGING ONLY
    # =========================================
    #echo "Config Directory: $CONFIG"
    #echo "Repo Directory: $REPO"
    #echo "Package Name: $pkgName"
    #echo "Package Path: $pkgPath"
    #echo "Last Path Item: $lastPathItem"
    #echo "New Path: $newPath"
    #echo "Moved to: $REPO/$pkgName/$newPath"
    # =========================================
    ;;

  "--version"|"-v")
    echo "udots Version ${VERSION}"
    ;;

  *)
    stow -d "$REPO" -t "$HOME" "$1"
    ;;
esac
